name: Build

on:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
    
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: BrowserStack env setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack local tunnel setup'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - bash: |
          set -xeuo pipefail
          cd tests
          yarn serve &
          sleep 10 # give the local service time to start up
          yarn bs-local -e default,firefox,edge,safari -o reports
          pkill -f vue-cli-service # stop the servers
        displayName: Run BrowserStack tests
